//! Input events and lifecycle notifications.
//!
//! [`Event<T>`] is the top-level event type dispatched through the widget tree.
//! The `T` parameter is a user-defined custom event payload; it defaults to `()`
//! (no custom events) so simple apps need no type annotation.
//!
//! ## Routing
//!
//! Events are dispatched depth-first: leaf widgets are offered the event first.
//! Each widget returns [`EventResult::Consumed`] to stop propagation or
//! [`EventResult::Bubble`] to pass it to the parent.
//!
//! [`Event::Custom`] variants are not currently routed to individual widgets -
//! they are stripped at the tree boundary. This will change when the effect
//! system lands.
//!
//! ## Keyboard input
//!
//! For text editing, prefer [`Event::TextInput`] over [`Event::KeyDown`].
//! `TextInput` handles IME composition, dead keys, and OS-level key remapping.
//! Use `KeyDown` for non-text keys (navigation, shortcuts) and check
//! [`KeyDownEvent::text`] only when you need the raw produced character.

use crate::style::ViewportSize;

/// A logical key identity, independent of keyboard layout.
///
/// Primarily designed for a simple navigation system, which is why some keys are seperated from the [`Other`](`Key::Other`) variant.
///
/// [`Key::Char`] holds the **unshifted** glyph for the key - `'1'` for the `1/!`
/// key regardless of whether Shift is held. For the actual character produced by a
/// keypress, use [`KeyDownEvent::text`] instead.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Key {
    // Navigation
    ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
    Enter, Backspace, Delete, Tab, Escape, Space,

    // Modifiers
    Shift, Ctrl, Alt,
    /// Cmd on macOS, Win on Windows
    Meta,

    /// Function keys F1–F24
    F(u8),

    /// Printable key identified by its **unshifted** glyph.
    Char(char),

    /// A key Phosphor doesn't have a named variant for.
    Other(String),
}

/// Active modifier keys at the time of an event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Modifiers {
    pub shift: bool,
    pub ctrl:  bool,
    pub alt:   bool,
    /// Cmd on macOS, Win on Windows
    pub meta:  bool,
}

impl Modifiers {
    pub const NONE: Self = Self { shift: false, ctrl: false, alt: false, meta: false };

    /// Returns `true` if any modifier is active.
    pub fn any(&self) -> bool {
        self.shift || self.ctrl || self.alt || self.meta
    }
}

/// Payload for a key-press event.
///
/// `is_repeat` is only present here (not on [`KeyUpEvent`]) because auto-repeat
/// is a property of the press action only - a key-up always represents a
/// physical release.
#[derive(Debug, Clone, PartialEq)]
pub struct KeyDownEvent {
    pub key: Key,
    pub modifiers: Modifiers,
    /// The text this keypress produces, if any.
    ///
    /// Respects the active keyboard layout and compose sequences. Prefer this
    /// over `key` for text input - it correctly handles digraphs, dead keys,
    /// and IME pre-edit commits.
    pub text: Option<String>,
    /// `true` if this event was generated by the OS key-repeat mechanism.
    pub is_repeat: bool,
    /// OS-dependent keycode
    pub keycode: u32
}

/// Payload for a key-release event.
#[derive(Debug, Clone, PartialEq)]
pub struct KeyUpEvent {
    pub key: Key,
    pub modifiers: Modifiers,
    /// OS-dependent keycode
    pub keycode: u32
}

/// Opaque identifier for a connected gamepad.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct GamepadId(pub u32);

/// Physical button on a gamepad, using cross-platform semantic names.
///
/// Face button names follow the Xbox convention; the PlayStation equivalent is
/// noted in parentheses.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GamepadButton {
    // Face buttons
    /// A (Xbox) / Cross (PS) / B (Nintendo)
    South,
    /// B (Xbox) / Circle (PS) / A (Nintendo)
    East,
    /// X (Xbox) / Square (PS) / Y (Nintendo)
    West,
    /// Y (Xbox) / Triangle (PS) / X (Nintendo)
    North,

    // Shoulder / trigger buttons
    LeftBumper,
    RightBumper,
    LeftTrigger,
    RightTrigger,

    // Stick clicks
    LeftStick,
    RightStick,

    // D-pad
    DPadUp,
    DPadDown,
    DPadLeft,
    DPadRight,

    // Center buttons
    Start,
    Select,
    /// Xbox / PS / Nintendo home button.
    Home,
    Capture,

    /// A button index not covered by the named variants.
    Other(u32),
}

/// Axis on a gamepad.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GamepadAxis {
    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,
    LeftTrigger,
    RightTrigger,
    /// An axis index not covered by the named variants.
    Other(u32),
}

/// Payload for a gamepad button press or release.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GamepadButtonEvent {
    pub id:     GamepadId,
    pub button: GamepadButton,
    /// Analog pressure `[0.0, 1.0]`. Digital buttons report `0.0` or `1.0`.
    pub value:  f32,
}

/// Payload for a gamepad axis change.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GamepadAxisEvent {
    pub id:    GamepadId,
    pub axis:  GamepadAxis,
    /// Axis position `[-1.0, 1.0]`. Triggers use `[0.0, 1.0]`.
    pub value: f32,
}

/// Window and application lifecycle notifications.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LifecycleEvent {
    /// Window became visible and is ready to render.
    Resumed,
    /// Window is being hidden or backgrounded.
    Paused,
    /// Window was resized. Contains the new logical pixel dimensions.
    Resized(ViewportSize),
    /// The OS or user has requested the application to close.
    CloseRequested,
}

/// Focus gained or lost by the window.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FocusEvent {
    Gained,
    Lost,
}

/// A dispatched event, optionally carrying a user-defined custom payload.
///
/// `T` is the custom event type for this application; it defaults to `()`
/// so apps with no custom events need no annotation.
///
/// ## Routing note
///
/// [`Event::Custom`] is not currently routed to individual widgets - the tree
/// strips it before dispatch. All other variants are forwarded depth-first.
#[derive(Debug, Clone, PartialEq)]
pub enum Event<T = ()> {
    // Keyboard
    KeyDown(KeyDownEvent),
    KeyUp(KeyUpEvent),
    /// Processed text input from the OS.
    ///
    /// Handles IME, dead keys, and compose sequences. Prefer this over
    /// `KeyDown` for any text-entry widget.
    TextInput(String),

    // Gamepad
    GamepadConnected(GamepadId),
    GamepadDisconnected(GamepadId),
    GamepadButtonDown(GamepadButtonEvent),
    GamepadButtonUp(GamepadButtonEvent),
    GamepadAxisChanged(GamepadAxisEvent),

    // Focus
    Focus(FocusEvent),

    // Lifecycle
    Lifecycle(LifecycleEvent),

    /// User-defined event. Not currently routed to individual widgets.
    Custom(T),
}

/// Return value from [`Widget::on_event`](crate::widget::Widget::on_event).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventResult {
    /// The widget handled the event - stop propagation.
    Consumed,
    /// Not handled - pass to parent.
    Bubble,
}